const data = {
    products:[
        {
            _id:'1',
            name:'product1',
            category:'Shirts',
            image:'/images/p1.png',
            price:90,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'product2',
            category:'Shirts',
            image:'/images/p1.png',
            price:80,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'product3',
            category:'Shirts',
            image:'/images/p1.png',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'product4',
            category:'Shirts',
            image:'/images/p1.png',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'product5',
            category:'Shirts',
            image:'/images/p1.png',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'product6',
            category:'Shirts',
            image:'/images/p1.png',
            price:110,
            brand:'Addidas',
            rating:4,
            numReviews:15,
            description:'high quality product',
        },
    ],
}

export default data;